env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
rules:
  "react/jsx-one-expression-per-line": "off"
  "react/jsx-filename-extension": "off"
  "react/react-in-jsx-scope": "off"
  "no-unused-vars": "warn"
  "indent": ["error", 4] # Specifies a 2-space indentation
  "no-mixed-spaces-and-tabs": "error" # Disallows mixed spaces and tabs for indentation
